/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package posfinal;

import java.awt.Color;
import java.util.regex.Pattern;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;

/**
 *
 * @author gihon
 */

public class CashierEnd extends javax.swing.JFrame {
    Functions F = new Functions();
    CustomizeTable CT = new CustomizeTable();
    
    
    /**
     * Creates new form CashierEnd
     */
    public CashierEnd() {
        
        initComponents();
        jLabel2.setText("Hello ! "+F.CashierName);
        F.CSearchType(1);
        F.IsCartEmpty();
        OpenedMenue.setVisible(false);
        //Customization of Cart
        CT.changetablelayout(); 
        SearchPanelSmall.setVisible(false);
        QTYWindow.setVisible(false);
        DiscountPanel.setVisible(false);
        Error.setVisible(false);Error.setSize(0, 40);
        
        //Customization of SearchTableSmall
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel34 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        MainJpanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Minimize = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();
        DiscountPanel = new javax.swing.JPanel();
        ItemBTN = new javax.swing.JLabel();
        CartBTN = new javax.swing.JLabel();
        CartShadow = new javax.swing.JLabel();
        ItemShadow = new javax.swing.JLabel();
        DiscountName = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        PercentageDiscount = new javax.swing.JLabel();
        CashDiscount = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        DisInput = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        Textfielfshadow = new javax.swing.JLabel();
        DiscountCancel = new javax.swing.JLabel();
        DiscountRemove = new javax.swing.JLabel();
        DiscountOK = new javax.swing.JLabel();
        Error = new javax.swing.JPanel();
        ErrorText = new javax.swing.JLabel();
        SearchPanelSmall = new javax.swing.JPanel();
        SearchTablePanel = new javax.swing.JScrollPane();
        SearchTable = new javax.swing.JTable();
        QTYWindow = new javax.swing.JPanel();
        QuantityTitle = new javax.swing.JLabel();
        QTYEnter = new javax.swing.JTextField();
        QTYOK = new javax.swing.JLabel();
        QTYCANCEL = new javax.swing.JLabel();
        OpenedMenue = new javax.swing.JPanel();
        MenueOpened = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Dashboard = new javax.swing.JButton();
        ManageProducts = new javax.swing.JButton();
        Sales = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        Cashier = new javax.swing.JButton();
        Settings1 = new javax.swing.JButton();
        Stock = new javax.swing.JButton();
        ClosedMenue = new javax.swing.JPanel();
        MenueClosed = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        SearchName = new javax.swing.JLabel();
        SearchQr1 = new javax.swing.JLabel();
        SearchTag = new javax.swing.JLabel();
        Search = new javax.swing.JTextField();
        SearchSmallIcon = new javax.swing.JLabel();
        ScrollPanePTable = new javax.swing.JScrollPane();
        Cart = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        nt = new javax.swing.JLabel();
        Tax1 = new javax.swing.JLabel();
        s = new javax.swing.JLabel();
        NetTotal = new javax.swing.JLabel();
        SubTotal = new javax.swing.JLabel();
        realAmnt = new javax.swing.JLabel();
        Remove = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Quantity = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ClearItems = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Lock = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        Discount = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        Refund = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        Payment = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        Drawer = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        SubTotal1 = new javax.swing.JLabel();
        NetTot = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        NetTotal2 = new javax.swing.JLabel();
        Bal = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Card = new javax.swing.JLabel();
        Cash = new javax.swing.JLabel();
        CashIn = new javax.swing.JTextField();
        placeholder1 = new javax.swing.JLabel();

        jLabel34.setText("jLabel34");

        jLabel36.setText("jLabel36");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainJpanel.setBackground(new java.awt.Color(51, 51, 51));
        MainJpanel.setMaximumSize(new java.awt.Dimension(1366, 768));
        MainJpanel.setMinimumSize(new java.awt.Dimension(1366, 768));
        MainJpanel.setPreferredSize(new java.awt.Dimension(1366, 768));
        MainJpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Minimize.setBackground(new java.awt.Color(102, 102, 102));
        Minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posfinal/Icons/Minimize.png"))); // NOI18N
        Minimize.setOpaque(true);
        Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MinimizeMouseExited(evt);
            }
        });
        jPanel1.add(Minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 0, 43, 41));

        Exit.setBackground(new java.awt.Color(102, 102, 102));
        Exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posfinal/Icons/Exit.png"))); // NOI18N
        Exit.setOpaque(true);
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitMouseExited(evt);
            }
        });
        jPanel1.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1313, 0, 43, 41));

        MainJpanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, -1));

        DiscountPanel.setBackground(new java.awt.Color(102, 102, 102));
        DiscountPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.orange, null));
        DiscountPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ItemBTN.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        ItemBTN.setForeground(new java.awt.Color(255, 255, 255));
        ItemBTN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemBTN.setText("Item Discount");
        ItemBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ItemBTNMouseClicked(evt);
            }
        });
        DiscountPanel.add(ItemBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 130, 40));

        CartBTN.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        CartBTN.setForeground(new java.awt.Color(255, 255, 255));
        CartBTN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CartBTN.setText("Cart Discount");
        CartBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CartBTNMouseClicked(evt);
            }
        });
        DiscountPanel.add(CartBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 40));

        CartShadow.setBackground(new java.awt.Color(255, 255, 255));
        CartShadow.setOpaque(true);
        DiscountPanel.add(CartShadow, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 130, 2));

        ItemShadow.setBackground(new java.awt.Color(255, 255, 255));
        ItemShadow.setOpaque(true);
        DiscountPanel.add(ItemShadow, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 130, 2));

        DiscountName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DiscountName.setForeground(new java.awt.Color(255, 255, 255));
        DiscountName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DiscountName.setText("####");
        DiscountPanel.add(DiscountName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 300, -1));

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("Apply discount to ");
        DiscountPanel.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 300, -1));

        PercentageDiscount.setBackground(new java.awt.Color(102, 102, 102));
        PercentageDiscount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PercentageDiscount.setForeground(new java.awt.Color(255, 255, 255));
        PercentageDiscount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PercentageDiscount.setText("%");
        PercentageDiscount.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        PercentageDiscount.setOpaque(true);
        PercentageDiscount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PercentageDiscountMouseClicked(evt);
            }
        });
        DiscountPanel.add(PercentageDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 70, 30));

        CashDiscount.setBackground(new java.awt.Color(102, 102, 102));
        CashDiscount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CashDiscount.setForeground(new java.awt.Color(255, 255, 255));
        CashDiscount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CashDiscount.setText("$");
        CashDiscount.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        CashDiscount.setOpaque(true);
        CashDiscount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CashDiscountMouseClicked(evt);
            }
        });
        DiscountPanel.add(CashDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 70, 30));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("Discount");
        DiscountPanel.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 300, 30));

        DisInput.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DisInput.setForeground(new java.awt.Color(255, 255, 255));
        DisInput.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        DisInput.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        DisInput.setCaretColor(new java.awt.Color(255, 255, 255));
        DisInput.setOpaque(false);
        DisInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisInputActionPerformed(evt);
            }
        });
        DisInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                DisInputKeyReleased(evt);
            }
        });
        DiscountPanel.add(DisInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 230, 100, 30));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("#");
        DiscountPanel.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 230, 30, 30));

        Textfielfshadow.setBackground(new java.awt.Color(0, 206, 209));
        Textfielfshadow.setOpaque(true);
        DiscountPanel.add(Textfielfshadow, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 262, 130, 2));

        DiscountCancel.setBackground(new java.awt.Color(204, 0, 0));
        DiscountCancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DiscountCancel.setForeground(new java.awt.Color(255, 255, 255));
        DiscountCancel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DiscountCancel.setText("Cancel");
        DiscountCancel.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        DiscountCancel.setOpaque(true);
        DiscountCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DiscountCancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DiscountCancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DiscountCancelMouseExited(evt);
            }
        });
        DiscountPanel.add(DiscountCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 130, 35));

        DiscountRemove.setBackground(new java.awt.Color(204, 0, 0));
        DiscountRemove.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DiscountRemove.setForeground(new java.awt.Color(255, 255, 255));
        DiscountRemove.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DiscountRemove.setText("Remove All Discounts");
        DiscountRemove.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        DiscountRemove.setOpaque(true);
        DiscountRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DiscountRemoveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DiscountRemoveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DiscountRemoveMouseExited(evt);
            }
        });
        DiscountPanel.add(DiscountRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 280, 35));

        DiscountOK.setBackground(new java.awt.Color(0, 153, 0));
        DiscountOK.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DiscountOK.setForeground(new java.awt.Color(255, 255, 255));
        DiscountOK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DiscountOK.setText("Apply");
        DiscountOK.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        DiscountOK.setOpaque(true);
        DiscountOK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DiscountOKMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DiscountOKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DiscountOKMouseExited(evt);
            }
        });
        DiscountPanel.add(DiscountOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 130, 35));

        MainJpanel.add(DiscountPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 145, 300, 400));

        Error.setBackground(new java.awt.Color(255, 0, 0));
        Error.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ErrorText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Error.add(ErrorText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 260, 40));

        MainJpanel.add(Error, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 50, 280, 40));

        SearchPanelSmall.setOpaque(false);
        SearchPanelSmall.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SearchTablePanel.setBackground(new java.awt.Color(51, 51, 51));
        SearchTablePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        SearchTablePanel.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        SearchTablePanel.setOpaque(false);

        SearchTable.setBackground(new java.awt.Color(204, 204, 204));
        SearchTable.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        SearchTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ProName", "Price", "ID", "Stock"
            }
        ));
        SearchTable.setFocusable(false);
        SearchTable.setIntercellSpacing(new java.awt.Dimension(1, 0));
        SearchTable.setRowHeight(30);
        SearchTable.setSelectionBackground(new java.awt.Color(0, 153, 51));
        SearchTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        SearchTable.setShowGrid(true);
        SearchTable.setShowVerticalLines(false);
        SearchTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchTableMouseClicked(evt);
            }
        });
        SearchTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SearchTableKeyPressed(evt);
            }
        });
        SearchTablePanel.setViewportView(SearchTable);

        SearchPanelSmall.add(SearchTablePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 440));

        MainJpanel.add(SearchPanelSmall, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 620, 440));

        QTYWindow.setBackground(new java.awt.Color(153, 153, 153));
        QTYWindow.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        QTYWindow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        QuantityTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        QuantityTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        QTYWindow.add(QuantityTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 250, 40));

        QTYEnter.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        QTYEnter.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        QTYEnter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        QTYEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QTYEnterActionPerformed(evt);
            }
        });
        QTYEnter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                QTYEnterKeyReleased(evt);
            }
        });
        QTYWindow.add(QTYEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 80, 100, 40));

        QTYOK.setBackground(new java.awt.Color(0, 153, 51));
        QTYOK.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        QTYOK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        QTYOK.setText("OK");
        QTYOK.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        QTYOK.setOpaque(true);
        QTYOK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QTYOKMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                QTYOKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                QTYOKMouseExited(evt);
            }
        });
        QTYWindow.add(QTYOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 90, 40));

        QTYCANCEL.setBackground(new java.awt.Color(204, 51, 0));
        QTYCANCEL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        QTYCANCEL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        QTYCANCEL.setText("CANCEL");
        QTYCANCEL.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        QTYCANCEL.setOpaque(true);
        QTYCANCEL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QTYCANCELMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                QTYCANCELMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                QTYCANCELMouseExited(evt);
            }
        });
        QTYWindow.add(QTYCANCEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 90, 40));

        MainJpanel.add(QTYWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(558, 200, 250, 230));

        OpenedMenue.setBackground(new java.awt.Color(69, 69, 69));
        OpenedMenue.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, null, java.awt.Color.lightGray));
        OpenedMenue.setForeground(new java.awt.Color(255, 255, 255));
        OpenedMenue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OpenedMenueMouseClicked(evt);
            }
        });
        OpenedMenue.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenueOpened.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MenueOpened.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posfinal/Icons/Menue.png"))); // NOI18N
        MenueOpened.setToolTipText("");
        MenueOpened.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenueOpenedMouseClicked(evt);
            }
        });
        OpenedMenue.add(MenueOpened, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 60, 60));

        jLabel2.setBackground(new java.awt.Color(69, 69, 69));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Hello ! USERNAME");
        jLabel2.setOpaque(true);
        OpenedMenue.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 2, 180, 60));

        Dashboard.setBackground(new java.awt.Color(0, 102, 102));
        Dashboard.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Dashboard.setForeground(new java.awt.Color(255, 255, 255));
        Dashboard.setText("Dashboard");
        Dashboard.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Dashboard.setFocusPainted(false);
        Dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DashboardMouseClicked(evt);
            }
        });
        Dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DashboardActionPerformed(evt);
            }
        });
        OpenedMenue.add(Dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 260, 60));

        ManageProducts.setBackground(new java.awt.Color(0, 102, 102));
        ManageProducts.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ManageProducts.setForeground(new java.awt.Color(255, 255, 255));
        ManageProducts.setText("Manage Products");
        ManageProducts.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ManageProducts.setFocusPainted(false);
        ManageProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageProductsActionPerformed(evt);
            }
        });
        OpenedMenue.add(ManageProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 260, 60));

        Sales.setBackground(new java.awt.Color(0, 102, 102));
        Sales.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Sales.setForeground(new java.awt.Color(255, 255, 255));
        Sales.setText("Sales");
        Sales.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Sales.setFocusPainted(false);
        Sales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalesActionPerformed(evt);
            }
        });
        OpenedMenue.add(Sales, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 260, 60));

        Logout.setBackground(new java.awt.Color(0, 102, 102));
        Logout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Logout.setForeground(new java.awt.Color(255, 255, 255));
        Logout.setText("Log-out");
        Logout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Logout.setFocusPainted(false);
        OpenedMenue.add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, 260, 60));

        Cashier.setBackground(new java.awt.Color(0, 102, 102));
        Cashier.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Cashier.setForeground(new java.awt.Color(255, 255, 255));
        Cashier.setText("Cashier");
        Cashier.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Cashier.setFocusPainted(false);
        Cashier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CashierActionPerformed(evt);
            }
        });
        OpenedMenue.add(Cashier, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 260, 60));

        Settings1.setBackground(new java.awt.Color(0, 102, 102));
        Settings1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Settings1.setForeground(new java.awt.Color(255, 255, 255));
        Settings1.setText("Settings");
        Settings1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Settings1.setFocusPainted(false);
        Settings1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Settings1ActionPerformed(evt);
            }
        });
        OpenedMenue.add(Settings1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 260, 60));

        Stock.setBackground(new java.awt.Color(0, 102, 102));
        Stock.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Stock.setForeground(new java.awt.Color(255, 255, 255));
        Stock.setText("Manage Stock");
        Stock.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Stock.setFocusPainted(false);
        Stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StockActionPerformed(evt);
            }
        });
        OpenedMenue.add(Stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 260, 60));

        MainJpanel.add(OpenedMenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 41, 300, 727));

        ClosedMenue.setBackground(new java.awt.Color(69, 69, 69));
        ClosedMenue.setForeground(new java.awt.Color(255, 255, 255));
        ClosedMenue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClosedMenueMouseClicked(evt);
            }
        });
        ClosedMenue.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenueClosed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MenueClosed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posfinal/Icons/Menue.png"))); // NOI18N
        MenueClosed.setToolTipText("");
        MenueClosed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenueClosedMouseClicked(evt);
            }
        });
        ClosedMenue.add(MenueClosed, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));

        MainJpanel.add(ClosedMenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 41, 60, 727));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setMaximumSize(new java.awt.Dimension(1306, 727));
        jPanel2.setMinimumSize(new java.awt.Dimension(1306, 727));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SearchName.setBackground(new java.awt.Color(51, 51, 51));
        SearchName.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        SearchName.setForeground(new java.awt.Color(255, 255, 255));
        SearchName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SearchName.setText("ABC");
        SearchName.setOpaque(true);
        SearchName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchNameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SearchNameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SearchNameMouseExited(evt);
            }
        });
        jPanel2.add(SearchName, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 7, 50, 40));

        SearchQr1.setBackground(new java.awt.Color(51, 51, 51));
        SearchQr1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SearchQr1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posfinal/Icons/SearchbyQR.png"))); // NOI18N
        SearchQr1.setOpaque(true);
        SearchQr1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchQr1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SearchQr1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SearchQr1MouseExited(evt);
            }
        });
        jPanel2.add(SearchQr1, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 7, 50, 40));

        SearchTag.setBackground(new java.awt.Color(51, 51, 51));
        SearchTag.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SearchTag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posfinal/Icons/SearchbyTag.png"))); // NOI18N
        SearchTag.setOpaque(true);
        SearchTag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchTagMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SearchTagMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SearchTagMouseExited(evt);
            }
        });
        jPanel2.add(SearchTag, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 7, 50, 40));

        Search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Search.setForeground(new java.awt.Color(255, 255, 255));
        Search.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Search.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Search.setCaretColor(new java.awt.Color(255, 255, 255));
        Search.setOpaque(false);
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SearchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SearchKeyReleased(evt);
            }
        });
        jPanel2.add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 7, 620, 40));

        SearchSmallIcon.setBackground(new java.awt.Color(51, 51, 51));
        SearchSmallIcon.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        SearchSmallIcon.setForeground(new java.awt.Color(255, 255, 255));
        SearchSmallIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SearchSmallIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posfinal/Icons/SearchMiniIcon.png"))); // NOI18N
        SearchSmallIcon.setOpaque(true);
        jPanel2.add(SearchSmallIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 7, 50, 40));

        ScrollPanePTable.setBackground(new java.awt.Color(51, 51, 51));
        ScrollPanePTable.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ScrollPanePTable.setOpaque(false);

        Cart.setBackground(new java.awt.Color(51, 51, 51));
        Cart.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Cart.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Cart.setForeground(new java.awt.Color(255, 255, 255));
        Cart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product", "Quantity", "Price(RS)", "Discount", "Amount", "DiscountType", "Measurement", "ID"
            }
        ));
        Cart.setFillsViewportHeight(true);
        Cart.setFocusable(false);
        Cart.setRowHeight(40);
        Cart.setRowMargin(0);
        Cart.setSelectionBackground(new java.awt.Color(0, 153, 51));
        Cart.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Cart.setShowGrid(true);
        Cart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CartMouseClicked(evt);
            }
        });
        Cart.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CartKeyPressed(evt);
            }
        });
        ScrollPanePTable.setViewportView(Cart);

        jPanel2.add(ScrollPanePTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 57, 790, 520));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tax");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 650, 190, 30));

        nt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nt.setForeground(new java.awt.Color(255, 255, 255));
        nt.setText("Net-Total");
        jPanel2.add(nt, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 680, 190, 30));

        Tax1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Tax1.setForeground(new java.awt.Color(255, 255, 255));
        Tax1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Tax1.setText("0.0");
        jPanel2.add(Tax1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 650, 140, 30));

        s.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        s.setForeground(new java.awt.Color(255, 255, 255));
        s.setText("SubTotal");
        jPanel2.add(s, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 620, 190, 30));

        NetTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        NetTotal.setForeground(new java.awt.Color(255, 255, 255));
        NetTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        NetTotal.setText("0.0");
        jPanel2.add(NetTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 680, 140, 30));

        SubTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SubTotal.setForeground(new java.awt.Color(255, 255, 255));
        SubTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        SubTotal.setText("0.0");
        jPanel2.add(SubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 620, 140, 30));

        realAmnt.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        realAmnt.setForeground(new java.awt.Color(255, 255, 255));
        realAmnt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        realAmnt.setText("0.0");
        realAmnt.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(realAmnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 590, 120, 30));

        Remove.setBackground(new java.awt.Color(51, 51, 51));
        Remove.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, null));
        Remove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RemoveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RemoveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RemoveMouseExited(evt);
            }
        });
        Remove.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Delete");
        Remove.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 3, -1, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posfinal/Icons/Remove.png"))); // NOI18N
        Remove.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 230, 80));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Remove");
        Remove.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 230, 20));

        jPanel2.add(Remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 57, 230, 110));

        Quantity.setBackground(new java.awt.Color(51, 51, 51));
        Quantity.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, null));
        Quantity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuantityMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                QuantityMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                QuantityMouseExited(evt);
            }
        });
        Quantity.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("F1");
        Quantity.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 3, -1, -1));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posfinal/Icons/Quantity.png"))); // NOI18N
        Quantity.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 230, 80));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Quantity");
        Quantity.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 230, 20));

        jPanel2.add(Quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 57, 230, 110));

        ClearItems.setBackground(new java.awt.Color(51, 51, 51));
        ClearItems.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, null));
        ClearItems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClearItemsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ClearItemsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ClearItemsMouseExited(evt);
            }
        });
        ClearItems.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("F2");
        ClearItems.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 3, -1, -1));

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posfinal/Icons/trash.png"))); // NOI18N
        ClearItems.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 110, 80));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Clear Items");
        ClearItems.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 110, 20));

        jPanel2.add(ClearItems, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 600, 110, 110));

        Lock.setBackground(new java.awt.Color(51, 51, 51));
        Lock.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, null));
        Lock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LockMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LockMouseExited(evt);
            }
        });
        Lock.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("CTRL+L");
        Lock.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 3, -1, -1));

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posfinal/Icons/lock.png"))); // NOI18N
        Lock.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 110, 80));

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Lock");
        Lock.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 110, 20));

        jPanel2.add(Lock, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 600, 110, 110));

        Discount.setBackground(new java.awt.Color(51, 51, 51));
        Discount.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, null));
        Discount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DiscountMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DiscountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DiscountMouseExited(evt);
            }
        });
        Discount.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("F3");
        Discount.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 3, -1, -1));

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posfinal/Icons/discount.png"))); // NOI18N
        Discount.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 110, 80));

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Discount");
        Discount.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 110, 20));

        jPanel2.add(Discount, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 600, 110, 110));

        Refund.setBackground(new java.awt.Color(51, 51, 51));
        Refund.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, null));
        Refund.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RefundMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RefundMouseExited(evt);
            }
        });
        Refund.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("F4");
        Refund.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 3, -1, -1));

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posfinal/Icons/Refund.png"))); // NOI18N
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
        });
        Refund.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 110, 80));

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Refund");
        Refund.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 110, 20));

        jPanel2.add(Refund, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 600, 110, 110));

        Payment.setBackground(new java.awt.Color(51, 51, 51));
        Payment.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, null));
        Payment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PaymentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PaymentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PaymentMouseExited(evt);
            }
        });
        Payment.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("F5");
        Payment.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 3, -1, -1));

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posfinal/Icons/Payment.png"))); // NOI18N
        Payment.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 230, 80));

        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Payment");
        Payment.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 230, 20));

        jPanel2.add(Payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 470, 230, 110));

        Drawer.setBackground(new java.awt.Color(51, 51, 51));
        Drawer.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, null));
        Drawer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DrawerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DrawerMouseExited(evt);
            }
        });
        Drawer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("F6");
        Drawer.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 3, -1, -1));

        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posfinal/Icons/Drawer.png"))); // NOI18N
        Drawer.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 230, 80));

        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Drawer");
        Drawer.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 230, 20));

        jPanel2.add(Drawer, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 470, 230, 110));

        SubTotal1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SubTotal1.setForeground(new java.awt.Color(255, 255, 255));
        SubTotal1.setText("Net-Total");
        jPanel2.add(SubTotal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 280, 190, 30));

        NetTot.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        NetTot.setForeground(new java.awt.Color(255, 255, 255));
        NetTot.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        NetTot.setText("0.0");
        jPanel2.add(NetTot, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 280, 140, 30));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Payment");
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 320, 190, 30));

        NetTotal2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        NetTotal2.setForeground(new java.awt.Color(255, 255, 255));
        NetTotal2.setText("Balance");
        jPanel2.add(NetTotal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 360, 190, 30));

        Bal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Bal.setForeground(new java.awt.Color(255, 255, 255));
        Bal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Bal.setText("0.0");
        jPanel2.add(Bal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 360, 140, 30));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 354, 340, -1));

        Card.setBackground(new java.awt.Color(51, 51, 51));
        Card.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Card.setForeground(new java.awt.Color(255, 255, 255));
        Card.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Card.setText("Card");
        Card.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, null));
        Card.setOpaque(true);
        Card.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CardMouseExited(evt);
            }
        });
        jPanel2.add(Card, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 180, 230, 40));

        Cash.setBackground(new java.awt.Color(0, 102, 0));
        Cash.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Cash.setForeground(new java.awt.Color(255, 255, 255));
        Cash.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cash.setText("Cash");
        Cash.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, null));
        Cash.setOpaque(true);
        Cash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CashMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CashMouseExited(evt);
            }
        });
        jPanel2.add(Cash, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 180, 230, 40));

        CashIn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CashIn.setForeground(new java.awt.Color(255, 255, 255));
        CashIn.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        CashIn.setText("0.0");
        CashIn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        CashIn.setCaretColor(new java.awt.Color(255, 255, 255));
        CashIn.setOpaque(false);
        CashIn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CashInKeyReleased(evt);
            }
        });
        jPanel2.add(CashIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 320, 140, 30));

        placeholder1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        placeholder1.setForeground(new java.awt.Color(153, 153, 153));
        placeholder1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(placeholder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 7, 420, 40));

        MainJpanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 41, 1306, 727));

        getContentPane().add(MainJpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        System.exit(0);
        
    }//GEN-LAST:event_ExitMouseClicked

    private void ExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseEntered
        labelcolor(Exit,0,100,100);
    }//GEN-LAST:event_ExitMouseEntered

    private void ExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseExited
        labelcolor(Exit,102,102,102);
    }//GEN-LAST:event_ExitMouseExited

    private void MinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMouseClicked
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_MinimizeMouseClicked

    private void MinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMouseEntered
        labelcolor(Minimize,0,100,100);
    }//GEN-LAST:event_MinimizeMouseEntered

    private void MinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMouseExited
        labelcolor(Minimize,102,102,102);
    }//GEN-LAST:event_MinimizeMouseExited

    private void SearchQr1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchQr1MouseEntered
        if(SearchQr1.isEnabled()){
            labelcolor(SearchQr1,15,99,39);
        }
    }//GEN-LAST:event_SearchQr1MouseEntered

    private void SearchQr1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchQr1MouseExited
        if(SearchQr1.isEnabled()){
            labelcolor(SearchQr1,51,51,51);
        }
    }//GEN-LAST:event_SearchQr1MouseExited

    private void SearchTagMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchTagMouseEntered
        if(SearchTag.isEnabled()){
            labelcolor(SearchTag,15,99,39);
        }
    }//GEN-LAST:event_SearchTagMouseEntered

    private void SearchTagMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchTagMouseExited
        if(SearchTag.isEnabled()){
            labelcolor(SearchTag,51,51,51);
        }
    }//GEN-LAST:event_SearchTagMouseExited

    private void SearchNameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchNameMouseEntered
        if(SearchName.isEnabled()){
            labelcolor(SearchName,15,99,39);
        }
    }//GEN-LAST:event_SearchNameMouseEntered

    private void SearchNameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchNameMouseExited
        if(SearchName.isEnabled()){
            labelcolor(SearchName,51,51,51);
        }
    }//GEN-LAST:event_SearchNameMouseExited

    private void RemoveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemoveMouseEntered
        if(Remove.isEnabled()){
            Remove.setBackground(new java.awt.Color(54, 171, 173));
            
        }
    }//GEN-LAST:event_RemoveMouseEntered

    private void RemoveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemoveMouseExited
        if(Remove.isEnabled()){
            Remove.setBackground(new java.awt.Color(51, 51, 51));
        }
    }//GEN-LAST:event_RemoveMouseExited

    private void QuantityMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuantityMouseEntered
        if(Quantity.isEnabled()){
            Quantity.setBackground(new java.awt.Color(54, 171, 173));
        }
    }//GEN-LAST:event_QuantityMouseEntered

    private void QuantityMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuantityMouseExited
        if(Quantity.isEnabled()){
            Quantity.setBackground(new java.awt.Color(51, 51, 51));
        }
    }//GEN-LAST:event_QuantityMouseExited

    private void ClearItemsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearItemsMouseEntered
        if(ClearItems.isEnabled()){
            ClearItems.setBackground(new java.awt.Color(54, 171, 173));
        }
    }//GEN-LAST:event_ClearItemsMouseEntered

    private void ClearItemsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearItemsMouseExited
        if(ClearItems.isEnabled()){
            ClearItems.setBackground(new java.awt.Color(51, 51, 51));
        }
    }//GEN-LAST:event_ClearItemsMouseExited

    private void LockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LockMouseEntered
        if(Lock.isEnabled()){
            Lock.setBackground(new java.awt.Color(54, 171, 173));
        }
    }//GEN-LAST:event_LockMouseEntered

    private void LockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LockMouseExited
        if(Lock.isEnabled()){
            Lock.setBackground(new java.awt.Color(51, 51, 51));
        }
    }//GEN-LAST:event_LockMouseExited

    private void DiscountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DiscountMouseEntered
        if(Discount.isEnabled()){
            Discount.setBackground(new java.awt.Color(54, 171, 173));
        }
    }//GEN-LAST:event_DiscountMouseEntered

    private void DiscountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DiscountMouseExited
        if(Discount.isEnabled()){
            Discount.setBackground(new java.awt.Color(51, 51, 51));
        }
    }//GEN-LAST:event_DiscountMouseExited

    private void RefundMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RefundMouseEntered
        if(Refund.isEnabled()){
            Refund.setBackground(new java.awt.Color(54, 171, 173));
        }
    }//GEN-LAST:event_RefundMouseEntered

    private void RefundMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RefundMouseExited
        if(Refund.isEnabled()){
            Refund.setBackground(new java.awt.Color(51, 51, 51));
        }
    }//GEN-LAST:event_RefundMouseExited

    private void PaymentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PaymentMouseEntered
        if(Payment.isEnabled()){
            Payment.setBackground(new java.awt.Color(54, 171, 173));
        }
    }//GEN-LAST:event_PaymentMouseEntered

    private void PaymentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PaymentMouseExited
        if(Payment.isEnabled()){
            Payment.setBackground(new java.awt.Color(51, 51, 51));
        }
    }//GEN-LAST:event_PaymentMouseExited

    private void DrawerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DrawerMouseEntered
        if(Drawer.isEnabled()){
            Drawer.setBackground(new java.awt.Color(54, 171, 173));
        }
    }//GEN-LAST:event_DrawerMouseEntered

    private void DrawerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DrawerMouseExited
        if(Drawer.isEnabled()){
            Drawer.setBackground(new java.awt.Color(51, 51, 51));
        }
    }//GEN-LAST:event_DrawerMouseExited

    private void CashMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CashMouseEntered
        if(Cash.isEnabled()){
            Cash.setBackground(new java.awt.Color(54, 171, 173));
        }
    }//GEN-LAST:event_CashMouseEntered

    private void CashMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CashMouseExited
        if(Cash.isEnabled()){
            Cash.setBackground(new java.awt.Color(51, 51, 51));
        }
    }//GEN-LAST:event_CashMouseExited

    private void CardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CardMouseEntered
        if(Card.isEnabled()){
            Card.setBackground(new java.awt.Color(54, 171, 173));
        }
    }//GEN-LAST:event_CardMouseEntered

    private void CardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CardMouseExited
        if(Card.isEnabled()){
            Card.setBackground(new java.awt.Color(51, 51, 51));
        }
    }//GEN-LAST:event_CardMouseExited

    private void SearchQr1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchQr1MouseClicked
        if (SearchQr1.isEnabled()){
             F.CSearchType(1);
        }
    }//GEN-LAST:event_SearchQr1MouseClicked

    private void SearchTagMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchTagMouseClicked
        if (SearchTag.isEnabled()){
             F.CSearchType(2);
        }
    }//GEN-LAST:event_SearchTagMouseClicked

    private void SearchNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchNameMouseClicked
        if (SearchName.isEnabled()){
             F.CSearchType(3);
        }
    }//GEN-LAST:event_SearchNameMouseClicked

    private void SearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchKeyReleased
        int searchkeycode =evt.getKeyCode();
        F.SearchInputSwitch(searchkeycode,this,false);
    }//GEN-LAST:event_SearchKeyReleased

    private void SearchTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchTableMouseClicked
       int row=SearchTable.getSelectedRow();
       Object x=SearchTable.getValueAt(row, 2);
       F.SelectSearchedItem(x, Cart, placeholder1);
    }//GEN-LAST:event_SearchTableMouseClicked

    private void QTYOKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QTYOKMouseEntered
        if(QTYOK.isEnabled()){
            labelcolor(QTYOK,15,99,39);
        }
    }//GEN-LAST:event_QTYOKMouseEntered

    private void QTYOKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QTYOKMouseExited
        if(QTYOK.isEnabled()){
            labelcolor(QTYOK,0,153,51);
        }
    }//GEN-LAST:event_QTYOKMouseExited

    private void QTYCANCELMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QTYCANCELMouseEntered
        if(QTYCANCEL.isEnabled()){
            labelcolor(QTYCANCEL,204,30,0);
        }
    }//GEN-LAST:event_QTYCANCELMouseEntered

    private void QTYCANCELMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QTYCANCELMouseExited
        if(QTYCANCEL.isEnabled()){
            labelcolor(QTYCANCEL,204,51,0);
        }
    }//GEN-LAST:event_QTYCANCELMouseExited

    private void QTYOKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QTYOKMouseClicked
        if (Pattern.matches(F.ValidateDouble, QTYEnter.getText())) {
            QTYEnter.setBorder(new LineBorder(Color.black, 1));
            F.SetQuantitySearch(Cart, Double.parseDouble(QTYEnter.getText()));
        } else {
            QTYEnter.setBorder(new LineBorder(Color.red, 1));
        }
    }//GEN-LAST:event_QTYOKMouseClicked

    private void QuantityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuantityMouseClicked
        if(Quantity.isEnabled()){
            Quantity.setBackground(new java.awt.Color(51, 51, 51));
            F.QTYMODE=0;
            F.OpenQuantityMenue(Cart);
        }
    }//GEN-LAST:event_QuantityMouseClicked

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        if ("".equals(Search.getText())){
            Search.setText("");
            placeholder1.setText(F.SearchTempLable);
        }else if((F.ChangeSearchType==1||F.ChangeSearchType==2)&&!"".equals(Search.getText())){
            if (Pattern.matches(F.ValidateInt, Search.getText())){
                Search.setBorder(new LineBorder(Color.white, 1));
                F.EnteredQR=true;
                F.Search(Search.getText(),SearchTable,placeholder1);
                Search.setText("");
                placeholder1.setText(F.SearchTempLable);
            }else{
                Search.setBorder(new LineBorder(Color.red, 1));
            }
        } 
    }//GEN-LAST:event_SearchActionPerformed

    private void DiscountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DiscountMouseClicked
        if(Discount.isEnabled()){
            F.ChangeDisType=0;
            F.OpenDiscountPanel(Cart);
        }
    }//GEN-LAST:event_DiscountMouseClicked

    private void ItemBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItemBTNMouseClicked
        if(ItemBTN.isEnabled()){
            F.ChangeDisType=1;
            F.OpenDiscountPanel(Cart);
        }
        
    }//GEN-LAST:event_ItemBTNMouseClicked

    private void CartBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CartBTNMouseClicked
        if(CartBTN.isEnabled()){
            F.ChangeDisType=0;
            F.OpenDiscountPanel(Cart);
        }
    }//GEN-LAST:event_CartBTNMouseClicked

    private void CashDiscountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CashDiscountMouseClicked
        CashDiscount.setBackground(new java.awt.Color(0, 206, 209));
        PercentageDiscount.setBackground(new java.awt.Color(102,102,102));
        jLabel38.setText("$");
        F.SelectedDisType=1;
        DisInput.setText("0.0");
        F.ST(DisInput);
        DiscountOK.setEnabled(true);
    }//GEN-LAST:event_CashDiscountMouseClicked

    private void PercentageDiscountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PercentageDiscountMouseClicked
        PercentageDiscount.setBackground(new java.awt.Color(0, 206, 209));
        CashDiscount.setBackground(new java.awt.Color(102,102,102));
        jLabel38.setText("%");
        F.SelectedDisType=2;
        DisInput.setText("0.0");
        F.ST(DisInput);
        DiscountOK.setEnabled(true);
    }//GEN-LAST:event_PercentageDiscountMouseClicked

    private void DiscountOKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DiscountOKMouseClicked
        if(DiscountOK.isEnabled()){
            double x = 0.00;
            if (!"".equals(DisInput.getText())) {
                x = Double.valueOf(DisInput.getText());
            } else {
                x = 0.0;
            }
            F.ApplyDiscount(x, Cart);
        }
    }//GEN-LAST:event_DiscountOKMouseClicked

    private void DisInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DisInputKeyReleased
        int searchkeycode =evt.getKeyCode();
        switch (searchkeycode){
            case 27:
                F.setEnableRec(jPanel2, true);
                DiscountPanel.setVisible(false);
                F.IsCartEmpty();
                break;
            default:
                if (!"".equals(DisInput.getText())) {
                    if (Pattern.matches(F.ValidateDouble, DisInput.getText())) {
                        if (F.SelectedDisType == 2 && Double.valueOf(DisInput.getText()) > 100) {
                            DisInput.setForeground(Color.red);
                            DiscountOK.setEnabled(false);
                        } else {
                            DisInput.setForeground(Color.white);
                            DiscountOK.setEnabled(true);
                        }

                    } else {
                        DisInput.setForeground(Color.red);
                        DiscountOK.setEnabled(false);
                    }
                } else {
                    DisInput.setForeground(Color.white);
                    DiscountOK.setEnabled(true);
                }
                break;
        }
        
    }//GEN-LAST:event_DisInputKeyReleased

    private void QTYEnterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_QTYEnterKeyReleased
        int searchkeycode =evt.getKeyCode();
        switch (searchkeycode){
            case 27:
                F.setEnableRec(jPanel2, true);
                QTYWindow.setVisible(false);
                F.IsCartEmpty();
                break;
            default :
                if (!"".equals(QTYEnter.getText())) {
                    if (Pattern.matches(F.ValidateDouble, QTYEnter.getText())) {
                        QTYEnter.setForeground(Color.black);
                        QTYOK.setEnabled(true);
                    } else {
                        QTYEnter.setForeground(Color.red);
                        QTYOK.setEnabled(false);
                    }
                }
                break;
        }
        
    }//GEN-LAST:event_QTYEnterKeyReleased

    private void DiscountOKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DiscountOKMouseEntered
        if(DiscountOK.isEnabled()){
            DiscountOK.setBackground(new java.awt.Color(0, 100, 0));    
        }
    }//GEN-LAST:event_DiscountOKMouseEntered

    private void DiscountOKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DiscountOKMouseExited
        if(DiscountOK.isEnabled()){
            DiscountOK.setBackground(new java.awt.Color(0, 153, 0));        
        }
    }//GEN-LAST:event_DiscountOKMouseExited

    private void DiscountCancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DiscountCancelMouseEntered
        if (DiscountCancel.isEnabled()) {
            DiscountCancel.setBackground(new java.awt.Color(150, 0, 0));
        }

    }//GEN-LAST:event_DiscountCancelMouseEntered

    private void DiscountCancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DiscountCancelMouseExited
        if (DiscountCancel.isEnabled()) {
            DiscountCancel.setBackground(new java.awt.Color(204, 0, 0));
        }
    }//GEN-LAST:event_DiscountCancelMouseExited

    private void DiscountRemoveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DiscountRemoveMouseEntered
        if (DiscountRemove.isEnabled()) {
            DiscountRemove.setBackground(new java.awt.Color(150, 0, 0));
        }
    }//GEN-LAST:event_DiscountRemoveMouseEntered

    private void DiscountRemoveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DiscountRemoveMouseExited
        if (DiscountRemove.isEnabled()) {
            DiscountRemove.setBackground(new java.awt.Color(204, 0, 0));
        }
    }//GEN-LAST:event_DiscountRemoveMouseExited

    private void ClearItemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearItemsMouseClicked
       if(ClearItems.isEnabled()){
            int response = JOptionPane.showConfirmDialog(this, "Do you want to Empty the cart ?", "Select option", JOptionPane.YES_OPTION);
            if (response == JOptionPane.YES_OPTION) {
                F.RemoveItems(Cart);
            }
       }
    }//GEN-LAST:event_ClearItemsMouseClicked

    private void DiscountRemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DiscountRemoveMouseClicked
        F.RemoveDiscounts(Cart);
    }//GEN-LAST:event_DiscountRemoveMouseClicked

    private void RemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemoveMouseClicked
        if(Remove.isEnabled())
            F.RemoveItem(Cart);
    }//GEN-LAST:event_RemoveMouseClicked

    private void PaymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PaymentMouseClicked
        if(Payment.isEnabled()){
            if("0.0".equals(CashIn.getText())){
                F.ST(CashIn); 
            }else{
                int response = JOptionPane.showConfirmDialog(this, "End Sale ?", "Select option", JOptionPane.YES_OPTION);
                if (response == JOptionPane.YES_OPTION) {
                    F.ProceedPayment();
                } 
            }
        }
    }//GEN-LAST:event_PaymentMouseClicked

    private void CartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CartMouseClicked
        F.IsCartEmpty();
    }//GEN-LAST:event_CartMouseClicked

    private void CashInKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CashInKeyReleased
        if(CashIn.isEnabled()){
            int searchkeycode =evt.getKeyCode();
            switch (searchkeycode){
                case 116:
                    if (Payment.isEnabled()) {
                        if ("0.0".equals(CashIn.getText())) {
                            F.ST(CashIn);
                        } else {
                            int response = JOptionPane.showConfirmDialog(this, "End Sale ?", "Select option", JOptionPane.YES_OPTION);
                            if (response == JOptionPane.YES_OPTION) {
                                F.ProceedPayment();
                            }
                        }
                    }
                    break;
                default:
                    if (!"".equals(CashIn.getText())) {
                        if (Pattern.matches(F.ValidateDouble, CashIn.getText())) {
                            CashIn.setForeground(Color.white);
                            Bal.setText(String.valueOf(F.RoundDouble(Double.valueOf(CashIn.getText())) - Double.valueOf(NetTot.getText())));
                            F.IsCartEmpty();
                        } else {
                            CashIn.setForeground(Color.red);
                            Payment.setEnabled(false);
                        }
                    } else {
                        Bal.setText("0.0");
                        Payment.setEnabled(false);
                    }
            }
        }
    }//GEN-LAST:event_CashInKeyReleased

    private void DisInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisInputActionPerformed
        if(DiscountOK.isEnabled()){
            double x = 0.00;
            if (!"".equals(DisInput.getText())) {
                x = Double.valueOf(DisInput.getText());
            } else {
                x = 0.0;
            }
            F.ApplyDiscount(x, Cart);
        }
    }//GEN-LAST:event_DisInputActionPerformed

    private void QTYEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QTYEnterActionPerformed
        if (Pattern.matches(F.ValidateDouble, QTYEnter.getText())) {
            QTYEnter.setBorder(new LineBorder(Color.black, 1));
            F.SetQuantitySearch(Cart, Double.parseDouble(QTYEnter.getText()));
        } else {
            QTYEnter.setBorder(new LineBorder(Color.red, 1));
        }
    }//GEN-LAST:event_QTYEnterActionPerformed

    private void QTYCANCELMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QTYCANCELMouseClicked
        F.setEnableRec(jPanel2,true);
        QTYWindow.setVisible(false);
        F.IsCartEmpty();
    }//GEN-LAST:event_QTYCANCELMouseClicked

    private void DiscountCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DiscountCancelMouseClicked
        F.setEnableRec(jPanel2,true);
        DiscountPanel.setVisible(false);
        F.IsCartEmpty();
    }//GEN-LAST:event_DiscountCancelMouseClicked

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked

    }//GEN-LAST:event_jLabel25MouseClicked

    private void CartKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CartKeyPressed

    }//GEN-LAST:event_CartKeyPressed

    private void SearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchKeyPressed
              
    }//GEN-LAST:event_SearchKeyPressed

    private void SearchTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchTableKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchTableKeyPressed

    private void OpenedMenueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OpenedMenueMouseClicked
        
    }//GEN-LAST:event_OpenedMenueMouseClicked

    private void ClosedMenueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClosedMenueMouseClicked
        
    }//GEN-LAST:event_ClosedMenueMouseClicked

    private void MenueClosedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenueClosedMouseClicked
        F.setEnableRec(jPanel2,false);
        Thread th = new Thread() {
            @Override
            public void run() {
                try {
                    for(int i=60;i<301;i++){
                        Thread.sleep(1/9);
                        ClosedMenue.setSize(i, 727);
                    }
                    OpenedMenue.setVisible(true);
                    ClosedMenue.setVisible(false);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            }
        };
        th.start();
    }//GEN-LAST:event_MenueClosedMouseClicked

    private void MenueOpenedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenueOpenedMouseClicked
        Thread th = new Thread() {
            @Override
            public void run() {
                try {
                    for(int i=300;i>60;i--){
                        Thread.sleep(1/9);
                        OpenedMenue.setSize(i, 727);
                        ClosedMenue.setSize(60, 727);
                    }
                    ClosedMenue.setVisible(true);
                    OpenedMenue.setVisible(false);
                    F.setEnableRec(jPanel2,true);
                    F.CSearchType(F.ChangeSearchType);
                    F.IsCartEmpty();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            }
        };
        th.start();
    }//GEN-LAST:event_MenueOpenedMouseClicked

    private void DashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DashboardActionPerformed
        
        Dashboard LF= new Dashboard();
        LF.setVisible(true);
        LF.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_DashboardActionPerformed

    private void CashierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CashierActionPerformed
        
        CashierEnd LF= new CashierEnd();
        LF.setVisible(true);
        LF.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_CashierActionPerformed

    private void Settings1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Settings1ActionPerformed
        
        Settings LF= new Settings();
        LF.setVisible(true);
        LF.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_Settings1ActionPerformed

    private void StockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StockActionPerformed
        
        Stock LF= new Stock();
        LF.setVisible(true);
        LF.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_StockActionPerformed

    private void DashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardMouseClicked
       
    }//GEN-LAST:event_DashboardMouseClicked

    private void SalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalesActionPerformed
        
        Sales LF= new Sales();
        LF.setVisible(true);
        LF.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_SalesActionPerformed

    private void ManageProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageProductsActionPerformed
        
        ManageProducts LF= new ManageProducts();
        LF.setVisible(true);
        LF.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_ManageProductsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashierEnd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashierEnd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashierEnd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashierEnd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CashierEnd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel Bal;
    private javax.swing.JLabel Card;
    public static javax.swing.JTable Cart;
    public static javax.swing.JLabel CartBTN;
    public static javax.swing.JLabel CartShadow;
    private javax.swing.JLabel Cash;
    public static javax.swing.JLabel CashDiscount;
    public static javax.swing.JTextField CashIn;
    private javax.swing.JButton Cashier;
    public static javax.swing.JPanel ClearItems;
    private javax.swing.JPanel ClosedMenue;
    private javax.swing.JButton Dashboard;
    public static javax.swing.JTextField DisInput;
    public static javax.swing.JPanel Discount;
    private javax.swing.JLabel DiscountCancel;
    public static javax.swing.JLabel DiscountName;
    private javax.swing.JLabel DiscountOK;
    public static javax.swing.JPanel DiscountPanel;
    private javax.swing.JLabel DiscountRemove;
    private javax.swing.JPanel Drawer;
    public static javax.swing.JPanel Error;
    public static javax.swing.JLabel ErrorText;
    private javax.swing.JLabel Exit;
    public static javax.swing.JLabel ItemBTN;
    public static javax.swing.JLabel ItemShadow;
    private javax.swing.JPanel Lock;
    private javax.swing.JButton Logout;
    private javax.swing.JPanel MainJpanel;
    private javax.swing.JButton ManageProducts;
    private javax.swing.JLabel MenueClosed;
    private javax.swing.JLabel MenueOpened;
    private javax.swing.JLabel Minimize;
    public static javax.swing.JLabel NetTot;
    public static javax.swing.JLabel NetTotal;
    private javax.swing.JLabel NetTotal2;
    private javax.swing.JPanel OpenedMenue;
    public static javax.swing.JPanel Payment;
    public static javax.swing.JLabel PercentageDiscount;
    public static javax.swing.JLabel QTYCANCEL;
    public static javax.swing.JTextField QTYEnter;
    public static javax.swing.JLabel QTYOK;
    public static javax.swing.JPanel QTYWindow;
    public static javax.swing.JPanel Quantity;
    public static javax.swing.JLabel QuantityTitle;
    private javax.swing.JPanel Refund;
    public static javax.swing.JPanel Remove;
    private javax.swing.JButton Sales;
    public static javax.swing.JScrollPane ScrollPanePTable;
    public static javax.swing.JTextField Search;
    public static javax.swing.JLabel SearchName;
    public static javax.swing.JPanel SearchPanelSmall;
    public static javax.swing.JLabel SearchQr1;
    private javax.swing.JLabel SearchSmallIcon;
    public static javax.swing.JTable SearchTable;
    public static javax.swing.JScrollPane SearchTablePanel;
    public static javax.swing.JLabel SearchTag;
    private javax.swing.JButton Settings1;
    private javax.swing.JButton Stock;
    public static javax.swing.JLabel SubTotal;
    private javax.swing.JLabel SubTotal1;
    public static javax.swing.JLabel Tax1;
    public static javax.swing.JLabel Textfielfshadow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    public static javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    public static javax.swing.JLabel jLabel37;
    public static javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel nt;
    public static javax.swing.JLabel placeholder1;
    public static javax.swing.JLabel realAmnt;
    private javax.swing.JLabel s;
    // End of variables declaration//GEN-END:variables
    private void labelcolor(JLabel label,int x,int y,int z) {
        label.setBackground(new java.awt.Color(x, y, z));
    }

}
